### ISSUE TITLE
Incorrect Ignition URL Kernel Param

### ISSUE THREAD

**Issue by ahmbas** [chuckersjp/coreos-iso-maker#1]
Thanks for setting up this repo. Saved me a ton of time creating the ISO's for setting the static IPs.
Just wanted to point out that the param should be "ignition_url" in this line, not image_url
https://github.com/chuckersjp/coreos-iso-maker/blob/5ab4bdb4325975c30388c7ad96b92f6f72ddadc7/playbook.yml#L58

**Comment by chuckersjp** [comment]
Thanks for pointing this out.  Corrected in latest version.
