### ISSUE TITLE
Switch to version 4.6

### ISSUE THREAD

**Issue by lukyky414** [chuckersjp/coreos-iso-maker#12]
Hello,

I've worked on switching to the version 4.6 of OpenShift.
The solution is simple (but I didnt find a better way to send a message other than an Issue)
Please take a look at the fork on Its4u: 
https://github.com/its4u/coreos-iso-maker

On the branch "v4.6", the solution is:
adding an option on the isolunix file (currently only on single-dhcp): coreos.liveiso=RHCOS-x86_64
because on the playbook:  /usr/bin/mkisofs [...] -A 'RHCOS-x86_64' [...]

the coreos.liveiso should be the app id. On the iso, the default is rhcos-46.82.202010091720-0, but since the playbook create another iso, it is another app id.

Not related, but the repo on its4u present 3 fixes:
first (on the branch dhcp), a patch to use dhcp
and (on the branch path), a patch to use custom folder in the web_server to pull ignition file or image file

second (on the branch dhcpANDpath): both patch together
third (on the branch v4.6): using the dhcpANDpath patch, I've added the v4.6 patch.
(maybe some parameters on isolinux are useless, I've put them all just in case).
The grub.cfg file is also useless in 4.6 (at least I didnt need it)

**Comment by lukyky414** [comment]
I'd like to add:

The difference on v4.6 is that the iso is a live version of coreos.

First change: the 'iso_name' now is '-live' instead of '-installer'.

Second: there is no need to use a image file together with the installation iso.
It is possible to add some code, to automatically ignore the 'coreos.inst.image_url' parameter if 'rhcos_bios' is not provided.

**Comment by chuckersjp** [comment]
Oooh....thanks for that.

Let me try an figure out how to put that in there.  There is a lot of new things with 4.6 that don't seem to be documented.
Hopefully I will get to it later today.

**Comment by lukyky414** [comment]
Resolved in Pull Request https://github.com/chuckersjp/coreos-iso-maker/pull/13 .
