### ISSUE TITLE
Add a little more detail around ignition files

### ISSUE THREAD

**Issue by ddreggors** [chuckersjp/coreos-iso-maker#17]
Could you add some more detail to the README with regards to creating individual ignition files. Is there a link to documentation that we could use here or could there be some small description of the process?

Most baremetal UPI and IPI install docs show how to create the generic bootstrap, master, and worker ignition files, but this playbook seems to require an ignition for each individual node on a webserver.

**Comment by chuckersjp** [comment]
Ignition files are created by the openshift-install binary that needs to be run at some point.  It doesn't necessarily need to be done BEFORE this but you do need to create them and put them somewhere.  These playbooks just auto wrap a pointer to those locations.

This mentions some of the procedure:
https://docs.openshift.com/container-platform/4.6/installing/install_config/installing-customizing.html

**Comment by ddreggors** [comment]
Yes, and that was what I was referring to when I said "Most baremetal UPI and IPI install docs show how to create the generic bootstrap, master, and worker ignition files". The issue is there is nothing in that link that mentions how to build specific ignition files. That document tells how to add machine configs to a master or worker ignition, but not how to make the "master" ignition (generic for all masters) into an individual ignition (specific to master0 for example with name/IP in it).

This is what is lacking I think

**Comment by chuckersjp** [comment]
David and I spoke a bit about this and agreed to close this issue.  There aren't individual ignition files, just "groups" of ignition files.
