### ISSUE TITLE
Isolinux generation problem

### ISSUE THREAD

**Issue by lukyky414** [chuckersjp/coreos-iso-maker#22]
Please make sure all .j2 file have a space after `{% include 'arguments.j2' %} `. It is important as the next charcater after the include is ignored.

Especially in isolinux.cfg-single.j2, where the End Of Line is ignored, making the menu list broken.

Sorry for the problematic pull request.

**Comment by lukyky414** [comment]
This need other characters. I'm investigating.

**Comment by lukyky414** [comment]
I confirm that only this space after include is needed on all .j2 file.

**Comment by chuckersjp** [comment]
Thanks.  Code updated and pushed.
